### ISSUE TITLE
MyRange - the operational headache cure Epic

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#1014]
- [ ] all things signature related 
- [x] all things user mgmt related
- [x] notification stuff
- [ ] all things FTA/client integration related
- [ ] pdf output stuff
- [ ] identifying workflow gaps - extensions, non use, versions
