### ISSUE TITLE
myrange extension UI + workflow

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#1051]
- [ ] new UI to show plans with required actions in list view
- [ ] 6 months before plan end date, and if plan has not been extended before, an email says 'you can request an extension, the plan expires on this date, you can request an extension for up to 5 years'. goes AH.  
- [ ] UI required action shows count of who has requested it, and total AH on plan, has button that gives yes/no
- [ ] when all have voted yes or no, staff get a notification
- [ ] if yes, staff get a button to do the extension
- [ ] if no, the required action dissapears
