### ISSUE TITLE
As a staff person I want to create a new pasture and update all related content so that it can be used in the schedule and content can be added

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#158]
# Requirements
- [x] "Add pasture" button prompts for name #133
- [x] Name is properly displayed #133
- [x] Default Allowable AUMs created/displayed #134, #135
- [x] Default Private Land Deduction (0) created/displayed #151 
- [x] Default Grace Days (1) created/displayed #152, #136
