### ISSUE TITLE
As a staff person I want to update content for all basic pasture fields so that the information is visible in the RUP

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#159]
# Requirements
- [x] update pasture name
- [x] update allowable AUMs
- [x] update private land deduction
- [x] update grace days
- [x] update pasture Notes
