### ISSUE TITLE
CRUD: As a staff person I want to delete a complete pasture so that only those pastures currently in the RUP area are visible

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#160]
# Requirements
- [ ] delete option visible
- [ ] reminder popup that delete is permanent
- [ ] reminder popup that all related plant communities, monitoring areas and criteria will also be deleted
- [ ] reminder popup that schedule rows with that pasture will be impacted
- [ ] pasture (including associated plant communities, monitoring areas and criteria) is deleted
- [ ] schedule rows having that pasture are deleted

#Definition of Done
- [ ] pasture and related content  deletes and no errors arise in schedule
