### ISSUE TITLE
As a staff person I want to add a plant community and update all information so the RUP content is complete

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#163]
# Requirements
- [x] required fields are identifiable (approved by minister, Plant Community Description) #162
- [x] "Add Plant Community" option visible
- [x] prompt to select plant community
- [x] if "other" selected from prompt second prompt for "name" triggers
- [x] name of new plant community displays
- [x] if "other" was selected the name entered in the prompt is displayed
- [x] view and update Aspect 
- [x] elevation options display 
- [x] update Elevation
- [x] update Approved By Minister toggle
- [x] Update Plant Community Description #142
- [x] Update Community URL
- [x] Update Purpose of Action to either establish or maintain
- [x] Plant Community Actions section not visible if Purpose of Action is "none" 
- [x] Update Purpose of Action back to blank

**Comment by LisaMoore1** [comment]
@calebissharp 
The two items below from the requirements (above) were working with the popup for "other" but they no longer are. See Issue #272

- if "other" selected from prompt second prompt for "name" triggers
- name of new plant community displays

Wondering if this had something to do with your work on the OTHER option for plant community actions and indicator species. I'm putting #272 as a bug into this sprint backlog so we make sure we don't actually push that regressed behaviour into PROD.
