### ISSUE TITLE
CRUD: As a staff member I want to add an action and fill in the details for an existing plant community so the content is complete

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#171]
# Requirements
- [x] "Add Action" button is visible #139
- [x] required fields clearly identified (Action, Details) #165
- [x] action dropdown display clearly #164
- [x] an action can be selected
- [x] selecting "Timing" displays the no graze period fields
- [x] no graze fields have a calendar showing mm and dd (no year) #166
- [x] date can be selected from no graze calendar
- [x] timing window fields captures calendar selection  #167
- [x] selecting "other" option opens prompt to provide a name #169
- [x] name provided for "other" option displays #169
- [x] selecting a option updates the placeholder text in the "details" field #170
