### ISSUE TITLE
CRUD: As a staff person I want to add readiness, stubble height and browse criteria to a plant community so the content is complete

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#172]
# Readiness Requirements
- [x] Readiness can be expressed as a date
- [x] readiness date has a calendar including mm and dd only #137 
- [X] date selected from calendar populates the field as mm dd only(not sure what it's doing with the year)
- [x]  Readiness can be expressed as text (test if that is what is labelled as "notes" #138 
- [x] Indicator Plant selection option is visible
- [ ] selecting it displays plant options cleanly #175
- [x] selecting a plant populated the Indicator Plant Field
- [x] selecting a plant populates the default value for the Criteria field #143 
- [x] Criteria is expressed to 1 decimal point #176
- [x] default criteria (leaf stage) is 0.0 #178
- [x] selecting "other" option opens popup to enter plant name #177
- [x] after selecting add on "other" popup the text entered is displayed in the indicator plant field

# Stubble Height Requirements
- [x] Add Indicator Plant selection option is visible
- [ ] selecting it displays plant options cleanly #175
- [x] selecting a plant populates the Indicator Plant field
- [x] selecting a plant populates the default value for the Height After Grazing (cm) field #143 
- [x] selecting "other" option opens popup to enter plant name #177
- [x] after selecting add on "other" popup the text entered is displayed in the indicator plant field
- [x] default value for Height After Grazing is 0.0 #178
- [x] Height After Grazing is expressed to 1 decimal point #176

# Browse Requirements
- [x] stubble height is expressed with zero decimal points #174
- [x] stubble height default is blank (null)
