### ISSUE TITLE
As a staff person I want to import criteria I select from an existing pasture/plant community that I identify into a selected plant community so that I don't have to duplicate data entry

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#173]
#Requirements
- [x] Import button is visible
- [x] popup to select a pasture is visible
- [x] popup to select a plant community from that pasture includes the communities from that pasture
- [ ] the community having data being imported IN should not be in the list if it's pasture is selected #
- [x] option to select WHICH criteria to import is available
- [ ] only those criteria that are selected import **needs testing**
- [x] warning popup regarding overwrite is displayed
- [ ] imported values overwrite existing content #140
