### ISSUE TITLE
CRUD: As a staff person I want to add a monitoring area to a plant community and update basic content so that content is complete

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#180]
# Requirements
- [x] Add Monitoring Area button available
- [x] selecting button opens popup to provide name for monitoring area
- [x] name provided displays in field #179
- [x] required fields are easily identifiable (location, rangeland health, purpose)
- [x] location field is visible and updateable
- [ ] rangeland health dropdown clearly shows options
- [x] selecting an option from the health dropdown populates the field
- [x] purpose field dropdown clearly shows options
- [x] selecting an option from the purpose dropdown populates the field
