### ISSUE TITLE
CRUD: As a staff person I want to delete individual elements of pasture data so the content is current

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#182]
# Requirements
- [ ] Plant Community delete option available #149
- [ ] popup pre-delete confirmation visible
- [x] Monitoring Area delete option available #181
- [x] popup pre-delete confirmation visible
- [x] Readiness indicator plant delete option available
- [x] popup pre-delete confirmation visible
- [x] Stubble Height indicator plant delete option available
- [x] popup -pre-delete confirmation visible
