### ISSUE TITLE
CRUD: As a staff person I want to add a Minister's Issue to the plan so the agreement holder knows what they need to provide actions for

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#194]
# Requirements
- [x] "Add Minister's Issue" button available
- [x] selecting button a clear selection list appears providing default including other
- [x] selecting an option populates the "Issue Type" label
- [x] selecting "other" from issues list raises prompt to name the issue type #192
- [x] text entered into "other" prompt is visible in the issue type label #192
- [ ] required fields are clearly identifiable (issue type, details, objective) #193
- [x] functioning "Identified by Minister" toggle available
- [x] option to select one or more pastures from pre-populated list
- [x] details field includes standard placeholder text #190
- [x] objective field contains standard placeholder text #191
