### ISSUE TITLE
CRUD: As a staff person I want to edit or delete an existing Minister's Issue to keep content current

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#195]
# Edit Requirements
- [ ]  Issue type can be edited #196
- [x] Pasture list can be edited
- [x] details content can be edited
- [x] objective content can be edited

# Delete Requirements
- [ ] delete issue option is available #197
- [ ] prompt notes that all issue content - including associated actions - will be deleted
- [ ] if confirmed the issue and associated actions is deleted
