### ISSUE TITLE
As a staff person I want to assist an agreement holder enter management consideration information so that if they aren't computer savvy they can still have a clean RUP

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#200]
**No specific issues exist for this user story as it is not a current workflow**

# Requirements
- [ ] add requirements button visible
- [ ] selecting button opens empty consideration fields
- [ ] required fields clearly identified (consideration, details)
- [ ] consideration dropdown list clearly shows concern, opportunity, other
- [ ] Selecting other does NOT require a prompt for a further name
- [ ] Default placeholder text need for details field (text needs to be developed)
- [ ] Details field accepts content
- [ ] URL field accepts content
- [ ]  delete management consideration option available
- [ ]  using delete option raises delete confirmation prompt
- [ ] if confirmed, consideration is deleted
