### ISSUE TITLE
As a staff member I want to create a PDF with all current information so that stakeholders and others can view a copy of the RUP

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#233]
# Lisa's Observations as of 2019-10-09
- [x] if an agreement holders has confirmed front page should indicate "signed on: the date on which they confirmed"
- [x] if an agreement holder has not yet confirmed it should note "Awaiting Signature"
- [x] text should not overlap
- [ ] for Actions (plant community or issues) is "other" is selected the "type" other is not needed -- just display the text provided
