### ISSUE TITLE
As a decision maker I want to log in to MyRangeBC view a work queue and identify those RUPs that require my attention so that I can work efficiently

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#258]
**Requirements**
- [ ] individual can be set up with an account specific to decision maker (using IDIR)
- [ ] decision maker may be assigned to more than one district
- [ ] each district has only one decision maker at a time
- [ ] on login decision maker has queue for view of *all* RUPs in their district
- [ ] decision maker can readily identify which RUPs are awaiting a decision
