### ISSUE TITLE
As a decision maker I want to delegate another individual to act as decision maker so someone can make decisions while I am away

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#260]
**REQUIREMENTS**
- [ ] decision maker (DM) can access MyRangeBC
- [ ] decision maker can send invite to other individual (internal to government) to act as delegate
- [ ] delegation can either be "with term" or "long term"
- [ ] if "with term" option then a start and end date for delegation period must be complete
- [ ] language as per delegation letter should be included (this will require someone from range branch pulling that language and confirming OK with legal crew) LM)
- [ ] delegation can be revoked/ended by the decision maker 
- [ ] find out if, when the DM provides a delegate if they can also still sign (LM)
