### ISSUE TITLE
As an agent I can receive and respond to agency related requests so that I can conduct business for those I represent

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#265]
**REQUIREMENTS**
- [ ] agents not having MyRA accounts receive information on obtaining an account
- [ ] when account is set up staff are notified (either automated or through notice to email staff contact)
- [ ] when agent has MyRA accounts receive notification to confirm agent status
- [ ] once agency agreement in place agents can log in to system using BCeID
- [ ] logged in agents see those RANs for which they are agents
- [ ] those agents that are also agreement holders can differentiate between their own agreements and those for which they are agents
- [ ] agents that are also AH on the same RAN can differentiate when they are signing for themselves versus others 
- [ ] where agents are acting on behalf of multiple individuals on a RAN (and themselves) they are able to minimize steps in identifying who they wish to sign/act for (one or more) for any given task
