### ISSUE TITLE
“Add Row” in schedule results in unexpected behavior 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#292]
**When adding a row in the schedule The expected behavior is:**
- [x] a notice identifies that there are invalid entries if any of the required fields are empty (see image #2)
- [x] the required fields are easily identifiable (see image #2)
- [x] calendar for both [date in] and [date out] defaults to the required year (year cannot be selected) and allow for selection of month and days only within that year (see image #3)
- [x] the table records the full date (including year) even though the front end displays only month and day in these fields (see image #4)
- [x] [date in] and [date out] should not accept the cursor and typing entry unless doing so actually updates the table (this is a bug in PROD 2019-11-12) (see Image #6)
- [ ] default grace days is visible but cannot be overwritten by the AH (there is a bug in PROD as of 2019-11-12 allowing AH to overwrite that field) (see image #3)
- [x] warning message that there are invalid entries disappears when a full row is entered (see image #4)
- [x] if total AUMs in the schedule exceed authorized AUMs a message indicates that it is not a valid entry (see image #5)

**Unexpected behavior in test 2019-11-12):**
- no notice that at least one row is required (see image #7)
- not all required fields identified as required (see image #7)
- date fields not displaying full date when maximized size in Safari - iOS (see image #8)
- grace days not pulling in from pasture (see image #9 — that pasture has a grace day of 1) 
- calendar picker is including year and defaulting to todays mm/dd (see image #8)
- AUM are calculating as though both dates are in same year even if the year was selected differently (which is a good thing and perhaps indicates that the table is actually getting the correct year regardless of what the calendar picker says?) (see image #9)
- after a completely valid schedule is entered there is still an error message for the year (see image #10)

![918932EC-78DF-44F8-A051-131220FC1AB0.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/b599439c-4f1a-4668-89b3-d251436324ca)
![2A13D6D6-BF7E-44F8-8675-C63DA55DBF1A.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f91832b6-8af3-403a-819f-9adde27adc35)
![A0E17B20-3121-4A4B-8C02-3980DDA6861D.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/4be984a2-c8d9-43d5-adb3-f7c8d2f932ff)
![73BD0BEB-2A93-4CF4-B75D-C091114113CF.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/653ceee3-69d3-4172-bcf2-d8515ca36e8c)
![44425CF0-A943-46B8-80D8-D33E1D38461E.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/7102e0bc-9ef6-497f-8413-3cfa0b1aea75)
![9212FE83-0E84-4E69-88EA-CDDD108FE101.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/3cb8c1cf-b5ae-41c6-8a89-cc41c2daa29b)
![6819E82F-F20C-40ED-8AA9-CD9E0308F6CF.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/7bea31de-a730-49d8-9a5a-e360aa8035f9)
![FE3CC2E0-A5C7-43F5-9CF8-AEC31B85A423.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/1116d915-bf7d-4d91-b374-986409ff2a4f)
![3968316D-0473-4E19-B000-A67522279FAB.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/b251195c-3c5f-4643-8a0d-0f418e99a3bb)
