### ISSUE TITLE
As an agreement holder I want to be able to add and update the content I am responsible for on the web so that I am ready to submit for feedback or decision. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#300]
**Agreement holders need to be able to add or update the following content: **
- [x] schedules #291, #292
- [x] actions for Minister's Issues #298, #297
- [x] Invasive Plant content
- [x] management considerations #299

**Agreement holder should NOT be able to add or update the following content:**
- [x] actions for plant communities #293
- [x] overwrite grace days in schedule rows #292
