### ISSUE TITLE
As a user I need to see the placeholder text whenever it is available so that I can make high quality entries into the fields.

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#350]
There are several fields that have context dependent placeholder text (ex. the placeholder text for [Details] depends on the action you have selected from the dropdown)

**Agreement Holders**
- [x] actions for Minister's Issues
- [x] schedule narrative

**Staff**
- [x] Pasture Notes #379
- [ ] Plant Community Description #380
- [x] Action for Plant Community Actions [Details] #170 
- [x] Minister's Issue [Details] #190 
- [x] Minister's Issue [ Objective] #191 
- [x] Actions for Minister's Issue (Detail?)
- [ ] Additional Requirements fields -- does not depend on the selection #381

**Comment by LisaMoore1** [comment]
@mccullochk There are a few user stories I'm wondering if you could take a look and consider for this sprint. We can talk later to discuss which you think would be best. This is one of them.  I'll tag you in another couple after lunch.

**Comment by calebissharp** [comment]
@LisaMoore1 Are these placeholder texts available anywhere?

**Comment by LisaMoore1** [comment]
@calebissharp These are the ones that are all in iPad. I can recreate a table with all of them in for you or you can refer to the iPad. Let me know what you prefer.

**Comment by calebissharp** [comment]
A table would be great please.
