### ISSUE TITLE
Agreement Holder is able to initiate and get desired amendments to staff

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#604]
**Applies to all amendment types**
- [ ] option visible to start amendment
- [ ] AH can edit plan (any content open to AH)
- [ ] option to save draft of amendment
- [ ] option to submit the amendment
   - [ ] prompts for explanation of amendment
   - [ ] opportunity to select amendment type 
   - [ ] language is clear on difference between amendment types
- [ ] signature gathering workflow initiated 
   - [ ] multi AH sub-workflow initiated if relevant
- [ ] option to change mind before submitted and clear it out of the system (completely delete it)
- [ ] immediately after "submit" option selected it is clear that an amendment is being created (no spinning wheel or other processing indicator makes user want to click repetitively)
- [ ] immediately after submit successful the header bar changes to indicate the amendment creation/status (so AH knows it has happened)

**Specific to Minor amendments**
- [ ] once signed by all the amended version becomes current legal version (could be "undone") -- easy to identify as current
- [ ] option to recall an amendment after it has been submitted to staff but before it enters staff review)

**Specific to Mandatory amendments**
- [ ] amendment is "draft" and no change is made to current legal version
- [ ] AH able to respond to feedback from staff related to the amendment
- [ ] feedback/update/approval process as for initial plans functions

**Comment by calebissharp** [comment]
@LisaMoore1 Is there a reason you closed this?

**Comment by LisaMoore1** [comment]
Because the other epic (#471) with the associated issues is probably more useful at this point. Feel free to do whatever makes the most sense to you.

**Comment by calebissharp** [comment]
@LisaMoore1 Oh gotcha, I didn't see that. Can you copy the checkboxes you put in this issue into #471? I found them pretty helpful.

**Comment by LisaMoore1** [comment]
@calebissharp Done.
